# # Global Electronics Retailer Analytics

Objective 

Analyze sales, profitability, customers, products, stores,

geography, and delivery performance for a multinational

electronics retailer from 2016 to 2020.

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
sales = pd.read_csv(r"C:\Users\visha\OneDrive\Desktop\Knowvation Learnings\DA Projects\Global Electronic retailer\Sales.csv")
sales.head(5)

,Order Number,Line Item,Order Date,Delivery Date,CustomerKey,StoreKey,ProductKey,Quantity,Currency Code
0,366000,1,1/1/2016,NaN,265598,10,1304,1,CAD
1,366001,1,1/1/2016,1/13/2016,1269051,0,1048,2,USD
2,366001,2,1/1/2016,1/13/2016,1269051,0,2007,1,USD
3,366002,1,1/1/2016,1/12/2016,266019,0,1106,7,CAD
4,366002,2,1/1/2016,1/12/2016,266019,0,373,1,CAD

In [4]:
sales.tail(5)

,Order Number,Line Item,Order Date,Delivery Date,CustomerKey,StoreKey,ProductKey,Quantity,Currency Code
62879,2243030,1,2/20/2021,NaN,1216913,43,632,3,USD
62880,2243031,1,2/20/2021,2/24/2021,511229,0,98,4,EUR
62881,2243032,1,2/20/2021,2/23/2021,331277,0,1613,2,CAD
62882,2243032,2,2/20/2021,2/23/2021,331277,0,1717,2,CAD
62883,2243032,3,2/20/2021,2/23/2021,331277,0,464,7,CAD

In [5]:
products = pd.read_csv(r"C:\Users\visha\OneDrive\Desktop\Knowvation Learnings\DA Projects\Global Electronic retailer\Products.csv")
products.head(5)

,ProductKey,Product Name,Brand,Color,Unit Cost USD,Unit Price USD,SubcategoryKey,Subcategory,CategoryKey,Category
0,1,Contoso 512MB MP3 Player E51 Silver,Contoso,Silver,$6.62,$12.99,101,MP4&MP3,1,Audio
1,2,Contoso 512MB MP3 Player E51 Blue,Contoso,Blue,$6.62,$12.99,101,MP4&MP3,1,Audio
2,3,Contoso 1G MP3 Player E100 White,Contoso,White,$7.40,$14.52,101,MP4&MP3,1,Audio
3,4,Contoso 2G MP3 Player E200 Silver,Contoso,Silver,$11.00,$21.57,101,MP4&MP3,1,Audio
4,5,Contoso 2G MP3 Player E200 Red,Contoso,Red,$11.00,$21.57,101,MP4&MP3,1,Audio

In [6]:
products.tail(5)

,ProductKey,Product Name,Brand,Color,Unit Cost USD,Unit Price USD,SubcategoryKey,Subcategory,CategoryKey,Category
2512,2513,Contoso Bluetooth Active Headphones L15 Red,Contoso,Red,$43.07,$129.99,505,Cell phones Accessories,5,Cell phones
2513,2514,Contoso Bluetooth Active Headphones L15 White,Contoso,White,$43.07,$129.99,505,Cell phones Accessories,5,Cell phones
2514,2515,Contoso In-Line Coupler E180 White,Contoso,White,$1.71,$3.35,505,Cell phones Accessories,5,Cell phones
2515,2516,Contoso In-Line Coupler E180 Black,Contoso,Black,$1.71,$3.35,505,Cell phones Accessories,5,Cell phones
2516,2517,Contoso In-Line Coupler E180 Silver,Contoso,Silver,$1.71,$3.35,505,Cell phones Accessories,5,Cell phones

In [7]:
customers = pd.read_csv(
    r"C:\Users\visha\OneDrive\Desktop\Knowvation Learnings\DA Projects\Global Electronic retailer\Customers.csv",
    encoding="latin1"
)

customers.head(5)

,CustomerKey,Gender,Name,City,State Code,State,Zip Code,Country,Continent,Birthday
0,301,Female,Lilly Harding,WANDEARAH EAST,SA,South Australia,5523,Australia,Australia,7/3/1939
1,325,Female,Madison Hull,MOUNT BUDD,WA,Western Australia,6522,Australia,Australia,9/27/1979
2,554,Female,Claire Ferres,WINJALLOK,VIC,Victoria,3380,Australia,Australia,5/26/1947
3,786,Male,Jai Poltpalingada,MIDDLE RIVER,SA,South Australia,5223,Australia,Australia,9/17/1957
4,1042,Male,Aidan Pankhurst,TAWONGA SOUTH,VIC,Victoria,3698,Australia,Australia,11/19/1965

In [8]:
customers.tail(5)

,CustomerKey,Gender,Name,City,State Code,State,Zip Code,Country,Continent,Birthday
15261,2099600,Female,Denisa Duková,Houston,TX,Texas,77017,United States,North America,3/25/1936
15262,2099618,Male,Justin Solórzano,Mclean,VA,Virginia,22101,United States,North America,2/16/1992
15263,2099758,Male,Svend Petrussen,Wilmington,NC,North Carolina,28405,United States,North America,11/9/1937
15264,2099862,Female,Lorenza Rush,Riverside,CA,California,92501,United States,North America,10/12/1937
15265,2099937,Male,Zygmunt Kaminski,Bloomfield Township,MI,Michigan,48302,United States,North America,8/18/1965

In [9]:
stores = pd.read_csv(r"C:\Users\visha\OneDrive\Desktop\Knowvation Learnings\DA Projects\Global Electronic retailer\Stores.csv")
stores.head(5)

   StoreKey    Country                         State  Square Meters  Open Date
0         1  Australia  Australian Capital Territory          595.0   1/1/2008
1         2  Australia            Northern Territory          665.0  1/12/2008
2         3  Australia               South Australia         2000.0   1/7/2012
3         4  Australia                      Tasmania         2000.0   1/1/2010
4         5  Australia                      Victoria         2000.0  12/9/2015

In [10]:
stores.tail(5)

    StoreKey        Country          State  Square Meters Open Date
62        63  United States           Utah         2000.0  3/6/2008
63        64  United States  Washington DC         1330.0  1/1/2010
64        65  United States  West Virginia         1785.0  1/1/2012
65        66  United States        Wyoming          840.0  1/1/2014
66         0         Online         Online            NaN  1/1/2010

In [11]:
exchange_rate = pd.read_csv(r"C:\Users\visha\OneDrive\Desktop\Knowvation Learnings\DA Projects\Global Electronic retailer\Exchange_Rates.csv")
exchange_rate.head(5)

       Date Currency  Exchange
0  1/1/2015      USD    1.0000
1  1/1/2015      CAD    1.1583
2  1/1/2015      AUD    1.2214
3  1/1/2015      EUR    0.8237
4  1/1/2015      GBP    0.6415

In [12]:
exchange_rate.tail(5)

            Date Currency  Exchange
11210  2/20/2021      USD    1.0000
11211  2/20/2021      CAD    1.2610
11212  2/20/2021      AUD    1.2723
11213  2/20/2021      EUR    0.8238
11214  2/20/2021      GBP    0.7126

In [13]:
data_dictionary = pd.read_csv(r"C:\Users\visha\OneDrive\Desktop\Knowvation Learnings\DA Projects\Global Electronic retailer\Data_Dictionary.csv")
data_dictionary.head(5)

   Table          Field                                        Description
0  Sales   Order Number                           Unique ID for each order
1  Sales      Line Item  Identifies individual products purchased as pa...
2  Sales     Order Date                          Date the order was placed
3  Sales  Delivery Date                       Date the order was delivered
4  Sales    CustomerKey  Unique key identifying which customer placed t...

In [14]:
data_dictionary.tail(5)

             Table          Field                       Description
32          Stores  Square Meters  Store footprint in square meters
33          Stores      Open Date                   Store open date
34  Exchange Rates           Date                              Date
35  Exchange Rates       Currency                     Currency code
36  Exchange Rates       Exchange     Exchange rate compared to USD

In [15]:
print("Sales:", sales.shape)
print("Customers:", customers.shape)
print("Products:", products.shape)
print("Stores:", stores.shape)
print("Exchange_Rate:", exchange_rate.shape)
print("Data Dictionary:", data_dictionary.shape)

Sales: (62884, 9)
Customers: (15266, 10)
Products: (2517, 10)
Stores: (67, 5)
Exchange_Rate: (11215, 3)
Data Dictionary: (37, 3)

In [16]:
datasets = {
    "Sales": sales,
    "Customers": customers,
    "Products": products,
    "Stores": stores,
    "Exchange_Rates": exchange_rate,
    "Data_Dictionary": data_dictionary
}

for name, df in datasets.items():
    print(f"\n--- {name} ---")
    print("Rows and columns:", df.shape)
    print("Total missing values:", df.isnull().sum().sum())
    print("Duplicate rows:", df.duplicated().sum())
    print("\nMissing values by column:")
    print(df.isnull().sum()[df.isnull().sum() > 0])

--- Sales ---
Rows and columns: (62884, 9)
Total missing values: 49719
Duplicate rows: 0

Missing values by column:
Delivery Date    49719
dtype: int64

--- Customers ---
Rows and columns: (15266, 10)
Total missing values: 10
Duplicate rows: 0

Missing values by column:
State Code    10
dtype: int64

--- Products ---
Rows and columns: (2517, 10)
Total missing values: 0
Duplicate rows: 0

Missing values by column:
Series([], dtype: int64)

--- Stores ---
Rows and columns: (67, 5)
Total missing values: 1
Duplicate rows: 0

Missing values by column:
Square Meters    1
dtype: int64

--- Exchange_Rates ---
Rows and columns: (11215, 3)
Total missing values: 0
Duplicate rows: 0

Missing values by column:
Series([], dtype: int64)

--- Data_Dictionary ---
Rows and columns: (37, 3)
Total missing values: 0
Duplicate rows: 0

Missing values by column:
Series([], dtype: int64)

In [17]:
for name, df in {
    "Sales": sales,
    "Customers": customers,
    "Products": products,
    "Stores": stores,
    "Exchange_Rates": exchange_rate
}.items():
    print(f"\n--- {name} ---")
    print(df.dtypes)
    print("\nSample values:")
    print(df.head(3).to_string(index=False))

--- Sales ---
Order Number     int64
Line Item        int64
Order Date         str
Delivery Date      str
CustomerKey      int64
StoreKey         int64
ProductKey       int64
Quantity         int64
Currency Code      str
dtype: object

Sample values:
 Order Number  Line Item Order Date Delivery Date  CustomerKey  StoreKey  ProductKey  Quantity Currency Code
       366000          1   1/1/2016           NaN       265598        10        1304         1           CAD
       366001          1   1/1/2016     1/13/2016      1269051         0        1048         2           USD
       366001          2   1/1/2016     1/13/2016      1269051         0        2007         1           USD

--- Customers ---
CustomerKey    int64
Gender           str
Name             str
City             str
State Code       str
State            str
Zip Code         str
Country          str
Continent        str
Birthday         str
dtype: object

Sample values:
 CustomerKey Gender          Name           City State Code             State Zip Code   Country Continent  Birthday
         301 Female Lilly Harding WANDEARAH EAST         SA   South Australia     5523 Australia Australia  7/3/1939
         325 Female  Madison Hull     MOUNT BUDD         WA Western Australia     6522 Australia Australia 9/27/1979
         554 Female Claire Ferres      WINJALLOK        VIC          Victoria     3380 Australia Australia 5/26/1947

--- Products ---
ProductKey        int64
Product Name        str
Brand               str
Color               str
Unit Cost USD       str
Unit Price USD      str
SubcategoryKey    int64
Subcategory         str
CategoryKey       int64
Category            str
dtype: object

Sample values:
 ProductKey                        Product Name   Brand  Color Unit Cost USD Unit Price USD  SubcategoryKey Subcategory  CategoryKey Category
          1 Contoso 512MB MP3 Player E51 Silver Contoso Silver        $6.62         $12.99              101     MP4&MP3            1    Audio
          2   Contoso 512MB MP3 Player E51 Blue Contoso   Blue        $6.62         $12.99              101     MP4&MP3            1    Audio
          3    Contoso 1G MP3 Player E100 White Contoso  White        $7.40         $14.52              101     MP4&MP3            1    Audio

--- Stores ---
StoreKey           int64
Country              str
State                str
Square Meters    float64
Open Date            str
dtype: object

Sample values:
 StoreKey   Country                        State  Square Meters Open Date
        1 Australia Australian Capital Territory          595.0  1/1/2008
        2 Australia           Northern Territory          665.0 1/12/2008
        3 Australia              South Australia         2000.0  1/7/2012

--- Exchange_Rates ---
Date            str
Currency        str
Exchange    float64
dtype: object

Sample values:
    Date Currency  Exchange
1/1/2015      USD    1.0000
1/1/2015      CAD    1.1583
1/1/2015      AUD    1.2214

In [18]:

# Convert Sales date columns to datetime

sales["Order Date"] = pd.to_datetime(
    sales["Order Date"],
    format="%m/%d/%Y",
    errors="coerce"
)

sales["Delivery Date"] = pd.to_datetime(
    sales["Delivery Date"],
    format="%m/%d/%Y",
    errors="coerce"
)

# Verify the conversion
print(sales[["Order Date", "Delivery Date"]].dtypes)

print("\nDate range:")
print("Earliest order:", sales["Order Date"].min())
print("Latest order:", sales["Order Date"].max())

print("\nMissing dates after conversion:")
print(sales[["Order Date", "Delivery Date"]].isnull().sum())

Order Date       datetime64[us]
Delivery Date    datetime64[us]
dtype: object

Date range:
Earliest order: 2016-01-01 00:00:00
Latest order: 2021-02-20 00:00:00

Missing dates after conversion:
Order Date           0
Delivery Date    49719
dtype: int64

In [19]:

print("Order Date samples:")
print(sales["Order Date"].head(10))

print("\nMissing Order Dates:", sales["Order Date"].isna().sum())
print("Missing Delivery Dates:", sales["Delivery Date"].isna().sum())

Order Date samples:
0   2016-01-01
1   2016-01-01
2   2016-01-01
3   2016-01-01
4   2016-01-01
5   2016-01-01
6   2016-01-01
7   2016-01-01
8   2016-01-01
9   2016-01-01
Name: Order Date, dtype: datetime64[us]

Missing Order Dates: 0
Missing Delivery Dates: 49719

In [20]:

# Inspect and clean product prices and costs

print("Before cleaning:")
print(products[["Unit Cost USD", "Unit Price USD"]].head())

for col in ["Unit Cost USD", "Unit Price USD"]:
    products[col] = (
        products[col]
        .str.replace("$", "", regex=False)
        .str.replace(",", "", regex=False)
        .astype(float)
    )

print("\nAfter cleaning:")
print(products[["Unit Cost USD", "Unit Price USD"]].head())

print("\nUpdated data types:")
print(products[["Unit Cost USD", "Unit Price USD"]].dtypes)

Before cleaning:
  Unit Cost USD Unit Price USD
0        $6.62         $12.99
1        $6.62         $12.99
2        $7.40         $14.52
3       $11.00         $21.57
4       $11.00         $21.57

After cleaning:
   Unit Cost USD  Unit Price USD
0           6.62           12.99
1           6.62           12.99
2           7.40           14.52
3          11.00           21.57
4          11.00           21.57

Updated data types:
Unit Cost USD     float64
Unit Price USD    float64
dtype: object

In [21]:


# Convert remaining date columns

customers["Birthday"] = pd.to_datetime(
    customers["Birthday"],
    format="%m/%d/%Y",
    errors="raise"
)

stores["Open Date"] = pd.to_datetime(
    stores["Open Date"],
    format="%m/%d/%Y",
    errors="raise"
)

exchange_rate["Date"] = pd.to_datetime(
    exchange_rate["Date"],
    format="%m/%d/%Y",
    errors="raise"
)

# Verify the conversion
print("Customers Birthday:", customers["Birthday"].dtype)
print("Stores Open Date:", stores["Open Date"].dtype)
print("Exchange Rates Date:", exchange_rate["Date"].dtype)

print("\nDate samples:")
print("Birthday:", customers["Birthday"].head(3).tolist())
print("Open Date:", stores["Open Date"].head(3).tolist())
print("Exchange Rate Date:", exchange_rate["Date"].head(3).tolist())

Customers Birthday: datetime64[us]
Stores Open Date: datetime64[us]
Exchange Rates Date: datetime64[us]

Date samples:
Birthday: [Timestamp('1939-07-03 00:00:00'), Timestamp('1979-09-27 00:00:00'), Timestamp('1947-05-26 00:00:00')]
Open Date: [Timestamp('2008-01-01 00:00:00'), Timestamp('2008-01-12 00:00:00'), Timestamp('2012-01-07 00:00:00')]
Exchange Rate Date: [Timestamp('2015-01-01 00:00:00'), Timestamp('2015-01-01 00:00:00'), Timestamp('2015-01-01 00:00:00')]

In [22]:

# Validate Sales data quality

print("1. Invalid or non-positive quantities:")
print((sales["Quantity"] <= 0).sum())

print("\n2. Duplicate order-line keys:")
print(sales.duplicated(subset=["Order Number", "Line Item"]).sum())

print("\n3. Order dates missing:")
print(sales["Order Date"].isna().sum())

print("\n4. Delivery dates earlier than order dates:")
invalid_delivery = (
    sales["Delivery Date"].notna()
    & (sales["Delivery Date"] < sales["Order Date"])
)
print(invalid_delivery.sum())

print("\n5. Unique order numbers:")
print(sales["Order Number"].nunique())

print("\n6. Total sales rows:")
print(len(sales))

1. Invalid or non-positive quantities:
0

2. Duplicate order-line keys:
0

3. Order dates missing:
0

4. Delivery dates earlier than order dates:
0

5. Unique order numbers:
26326

6. Total sales rows:
62884

In [23]:

# Document the data cleaning and validation process

cleaning_log = pd.DataFrame([
    {
        "Dataset": "Sales",
        "Check or Change": "Converted Order Date and Delivery Date",
        "Result": "Dates converted to datetime; 49,719 delivery dates remain missing"
    },
    {
        "Dataset": "Sales",
        "Check or Change": "Duplicate rows",
        "Result": "No duplicate rows found"
    },
    {
        "Dataset": "Sales",
        "Check or Change": "Order-line key",
        "Result": "No duplicate Order Number + Line Item combinations"
    },
    {
        "Dataset": "Sales",
        "Check or Change": "Quantity validation",
        "Result": "No zero or negative quantities"
    },
    {
        "Dataset": "Sales",
        "Check or Change": "Delivery date validation",
        "Result": "No delivery dates earlier than order dates"
    },
    {
        "Dataset": "Products",
        "Check or Change": "Converted Unit Cost USD and Unit Price USD",
        "Result": "Removed currency symbols and converted values to numeric"
    },
    {
        "Dataset": "Customers",
        "Check or Change": "Missing State Code",
        "Result": "10 missing values retained for investigation"
    },
    {
        "Dataset": "Stores",
        "Check or Change": "Missing Square Meters",
        "Result": "1 missing value retained; not replaced with zero"
    }
])

print(cleaning_log.to_string(index=False))

  Dataset                            Check or Change                                                            Result
    Sales     Converted Order Date and Delivery Date Dates converted to datetime; 49,719 delivery dates remain missing
    Sales                             Duplicate rows                                           No duplicate rows found
    Sales                             Order-line key                No duplicate Order Number + Line Item combinations
    Sales                        Quantity validation                                    No zero or negative quantities
    Sales                   Delivery date validation                        No delivery dates earlier than order dates
 Products Converted Unit Cost USD and Unit Price USD          Removed currency symbols and converted values to numeric
Customers                         Missing State Code                      10 missing values retained for investigation
   Stores                      Missing Square Meters                  1 missing value retained; not replaced with zero

In [24]:
# Calculate Revenue, Cost, Profit, and Profit Margin

# Merge product prices and costs into Sales

sales = sales.merge(
    products[["ProductKey", "Unit Cost USD", "Unit Price USD"]],
    on="ProductKey",
    how="left",
    validate="many_to_one"
)

# Calculate financial metrics
sales["Revenue USD"] = sales["Quantity"] * sales["Unit Price USD"]
sales["Cost USD"] = sales["Quantity"] * sales["Unit Cost USD"]
sales["Profit USD"] = sales["Revenue USD"] - sales["Cost USD"]

sales["Profit Margin %"] = (
    sales["Profit USD"] / sales["Revenue USD"] * 100
)

# Verify the results
print("Sales shape after merge:", sales.shape)
print("\nFinancial calculations:")
print(
    sales[
        [
            "Quantity",
            "Unit Price USD",
            "Unit Cost USD",
            "Revenue USD",
            "Cost USD",
            "Profit USD",
            "Profit Margin %"
        ]
    ].head(10)
)

print("\nMissing values in financial columns:")
print(
    sales[
        ["Unit Price USD", "Unit Cost USD", "Revenue USD", "Cost USD", "Profit USD"]
    ].isna().sum()
)

Sales shape after merge: (62884, 15)

Financial calculations:
   Quantity  Unit Price USD  Unit Cost USD  Revenue USD  Cost USD  Profit USD  \
0         1           68.00          31.27        68.00     31.27       36.73
1         2          427.00         141.47       854.00    282.94      571.06
2         1          665.94         220.64       665.94    220.64      445.30
3         7          322.00         148.08      2254.00   1036.56     1217.44
4         1          326.00         166.20       326.00    166.20      159.80
5         4          646.00         214.03      2584.00    856.12     1727.88
6         6         1592.20         527.53      9553.20   3165.18     6388.02
7         2          255.00         117.27       510.00    234.54      275.46
8         4          469.00         215.68      1876.00    862.72     1013.28
9         1           57.99          26.67        57.99     26.67       31.32

   Profit Margin %
0        54.014706
1        66.868852
2        66.867886
3        54.012422
4        49.018405
5        66.868421
6        66.867856
7        54.011765
8        54.012793
9        54.009312

Missing values in financial columns:
Unit Price USD    0
Unit Cost USD     0
Revenue USD       0
Cost USD          0
Profit USD        0
dtype: int64

In [25]:
# Validate product matching and financial calculations

print("Sales rows:", len(sales))
print("Missing ProductKey:", sales["ProductKey"].isna().sum())

print(
    "Missing product prices:",
    sales["Unit Price USD"].isna().sum()
)

print(
    "Missing product costs:",
    sales["Unit Cost USD"].isna().sum()
)

print(
    "Negative profit rows:",
    (sales["Profit USD"] < 0).sum()
)

print(
    "Zero or negative revenue rows:",
    (sales["Revenue USD"] <= 0).sum()
)

print("\nFinancial summary:")
print(
    sales[
        ["Revenue USD", "Cost USD", "Profit USD", "Profit Margin %"]
    ].describe().round(2)
)

Sales rows: 62884
Missing ProductKey: 0
Missing product prices: 0
Missing product costs: 0
Negative profit rows: 0
Zero or negative revenue rows: 0

Financial summary:
       Revenue USD  Cost USD  Profit USD  Profit Margin %
count     62884.00  62884.00    62884.00         62884.00
mean        886.64    367.23      519.41            54.90
std        1648.48    614.55     1052.20             6.41
min           0.95      0.48        0.47            48.95
25%         115.00     52.88       61.56            49.02
50%         360.00    164.16      194.44            54.01
75%         969.00    423.08      540.14            54.02
max       31999.90  10602.20    21397.70            66.89

In [26]:
print("Cleaning log columns:")
print(cleaning_log.columns.tolist())

print("\nNumber of columns:", len(cleaning_log.columns))

print("\nCurrent cleaning log:")
display(cleaning_log.tail())

Cleaning log columns:
['Dataset', 'Check or Change', 'Result']

Number of columns: 3

Current cleaning log:

,Dataset,Check or Change,Result
3,Sales,Quantity validation,No zero or negative quantities
4,Sales,Delivery date validation,No delivery dates earlier than order dates
5,Products,Converted Unit Cost USD and Unit Price USD,Removed currency symbols and converted values ...
6,Customers,Missing State Code,10 missing values retained for investigation
7,Stores,Missing Square Meters,1 missing value retained; not replaced with zero

In [27]:
cleaning_log.loc[len(cleaning_log)] = [
    "Sales",
    "Financial metrics",
    "Merged product prices and costs; calculated Revenue USD, Cost USD, Profit USD, and Profit Margin %. All 62,884 rows retained, with no missing financial values."
]

display(cleaning_log.tail(3))

,Dataset,Check or Change,Result
6,Customers,Missing State Code,10 missing values retained for investigation
7,Stores,Missing Square Meters,1 missing value retained; not replaced with zero
8,Sales,Financial metrics,Merged product prices and costs; calculated Re...

In [28]:
# Calculate delivery days
# Delivery Days = Delivery Date − Order Date
# Calculate delivery days
sales["Delivery Days"] = (
    sales["Delivery Date"] - sales["Order Date"]
).dt.days

# Validate delivery days
print("Missing delivery dates:", sales["Delivery Date"].isna().sum())
print("Missing delivery days:", sales["Delivery Days"].isna().sum())

print(
    "Negative delivery days:",
    (sales["Delivery Days"] < 0).sum()
)

print("\nDelivery days summary:")
print(sales["Delivery Days"].describe())

print("\nSample records:")
display(
    sales[
        ["Order Date", "Delivery Date", "Delivery Days"]
    ].head(10)
)

Missing delivery dates: 49719
Missing delivery days: 49719
Negative delivery days: 0

Delivery days summary:
count    13165.000000
mean         4.529130
std          2.121071
min          1.000000
25%          3.000000
50%          4.000000
75%          6.000000
max         17.000000
Name: Delivery Days, dtype: float64

Sample records:

  Order Date Delivery Date  Delivery Days
0 2016-01-01           NaT            NaN
1 2016-01-01    2016-01-13           12.0
2 2016-01-01    2016-01-13           12.0
3 2016-01-01    2016-01-12           11.0
4 2016-01-01    2016-01-12           11.0
5 2016-01-01    2016-01-12           11.0
6 2016-01-01           NaT            NaN
7 2016-01-01           NaT            NaN
8 2016-01-01           NaT            NaN
9 2016-01-01           NaT            NaN

In [29]:
cleaning_log.loc[len(cleaning_log)] = [
    "Sales",
    "Delivery days",
    "Calculated Delivery Days from Order Date and Delivery Date. 13,165 valid delivery records; 49,719 missing dates preserved; no negative delivery days."
]

display(cleaning_log.tail(4))

,Dataset,Check or Change,Result
6,Customers,Missing State Code,10 missing values retained for investigation
7,Stores,Missing Square Meters,1 missing value retained; not replaced with zero
8,Sales,Financial metrics,Merged product prices and costs; calculated Re...
9,Sales,Delivery days,Calculated Delivery Days from Order Date and D...

In [30]:
# customer and store data
# Check customer birthday data
print("CUSTOMER DATA")
print("Total customers:", len(customers))
print("Missing birthdays:", customers["Birthday"].isna().sum())
print("Earliest birthday:", customers["Birthday"].min())
print("Latest birthday:", customers["Birthday"].max())

# Check store opening dates
print("\nSTORE DATA")
print("Total stores:", len(stores))
print("Missing opening dates:", stores["Open Date"].isna().sum())
print("Earliest opening date:", stores["Open Date"].min())
print("Latest opening date:", stores["Open Date"].max())

# Check for future dates relative to the sales data
print("\nDATE VALIDATION")
print(
    "Birthdays after latest order date:",
    (customers["Birthday"] > sales["Order Date"].max()).sum()
)

print(
    "Store opening dates after latest order date:",
    (stores["Open Date"] > sales["Order Date"].max()).sum()
)

CUSTOMER DATA
Total customers: 15266
Missing birthdays: 0
Earliest birthday: 1935-02-03 00:00:00
Latest birthday: 2002-02-18 00:00:00

STORE DATA
Total stores: 67
Missing opening dates: 0
Earliest opening date: 2005-03-04 00:00:00
Latest opening date: 2019-03-05 00:00:00

DATE VALIDATION
Birthdays after latest order date: 0
Store opening dates after latest order date: 0

In [31]:
# What age groups are buying from the electronics retailer?
# Add customer birthdays to Sales
sales = sales.merge(
    customers[["CustomerKey", "Birthday"]],
    on="CustomerKey",
    how="left",
    validate="many_to_one"
)

# Calculate age at the time of each order
sales["Customer Age"] = (
    sales["Order Date"].dt.year
    - sales["Birthday"].dt.year
    - (
        (sales["Order Date"].dt.month < sales["Birthday"].dt.month)
        | (
            (sales["Order Date"].dt.month == sales["Birthday"].dt.month)
            & (sales["Order Date"].dt.day < sales["Birthday"].dt.day)
        )
    ).astype(int)
)

# Validate the results
print("Sales rows:", len(sales))
print("Missing birthdays:", sales["Birthday"].isna().sum())
print("Missing customer ages:", sales["Customer Age"].isna().sum())

print("\nCustomer age summary:")
print(sales["Customer Age"].describe())

print("\nSample results:")
display(
    sales[
        ["CustomerKey", "Order Date", "Birthday", "Customer Age"]
    ].head(10)
)

Sales rows: 62884
Missing birthdays: 0
Missing customer ages: 0

Customer age summary:
count    62884.000000
mean        49.486388
std         19.444818
min         14.000000
25%         33.000000
50%         49.000000
75%         66.000000
max         85.000000
Name: Customer Age, dtype: float64

Sample results:

   CustomerKey Order Date   Birthday  Customer Age
0       265598 2016-01-01 1971-03-23            44
1      1269051 2016-01-01 1995-11-20            20
2      1269051 2016-01-01 1995-11-20            20
3       266019 2016-01-01 1962-08-24            53
4       266019 2016-01-01 1962-08-24            53
5       266019 2016-01-01 1962-08-24            53
6      1107461 2016-01-01 1979-11-28            36
7      1107461 2016-01-01 1979-11-28            36
8       844003 2016-01-01 1995-06-22            20
9      2035771 2016-01-01 1944-10-30            71

In [32]:
# Create age groups
age_bins = [0, 17, 25, 35, 45, 55, 65, float("inf")]

age_labels = [
    "Under 18",
    "18-25",
    "26-35",
    "36-45",
    "46-55",
    "56-65",
    "66+"
]

sales["Customer Age Group"] = pd.cut(
    sales["Customer Age"],
    bins=age_bins,
    labels=age_labels,
    include_lowest=True
)

# Review the distribution
age_group_summary = (
    sales["Customer Age Group"]
    .value_counts(sort=False)
    .rename_axis("Customer Age Group")
    .reset_index(name="Sales Lines")
)

age_group_summary["Percentage"] = (
    age_group_summary["Sales Lines"]
    / len(sales) * 100
).round(2)

print(age_group_summary.to_string(index=False))

Customer Age Group  Sales Lines  Percentage
          Under 18         1335        2.12
             18-25         7694       12.24
             26-35         9259       14.72
             36-45         9391       14.93
             46-55         9392       14.94
             56-65         9401       14.95
               66+        16412       26.10

In [33]:
cleaning_log.loc[len(cleaning_log)] = [
    "Sales",
    "Customer age and age groups",
    "Merged customer birthdays, calculated age at order date, and created seven age groups. All 62,884 sales lines have valid ages and age groups."
]

display(cleaning_log.tail(3))

,Dataset,Check or Change,Result
8,Sales,Financial metrics,Merged product prices and costs; calculated Re...
9,Sales,Delivery days,Calculated Delivery Days from Order Date and D...
10,Sales,Customer age and age groups,"Merged customer birthdays, calculated age at o..."

In [34]:
# Calculate store age at the time of each sale
# Add store information to Sales
sales = sales.merge(
    stores[["StoreKey", "Open Date", "Square Meters", "Country"]],
    on="StoreKey",
    how="left",
    validate="many_to_one",
    suffixes=("", "_Store")
)

# Calculate store age in completed years at the time of each order
sales["Store Age"] = (
    sales["Order Date"].dt.year
    - sales["Open Date"].dt.year
    - (
        (sales["Order Date"].dt.month < sales["Open Date"].dt.month)
        | (
            (sales["Order Date"].dt.month == sales["Open Date"].dt.month)
            & (sales["Order Date"].dt.day < sales["Open Date"].dt.day)
        )
    ).astype(int)
)

# Validate the merge and calculation
print("Sales rows:", len(sales))
print("Missing store opening dates:", sales["Open Date"].isna().sum())
print("Missing store ages:", sales["Store Age"].isna().sum())
print("Negative store ages:", (sales["Store Age"] < 0).sum())

print("\nStore age summary:")
print(sales["Store Age"].describe())

print("\nSample records:")
display(
    sales[
        ["StoreKey", "Order Date", "Open Date", "Store Age"]
    ].head(10)
)

Sales rows: 62884
Missing store opening dates: 0
Missing store ages: 0
Negative store ages: 0

Store age summary:
count    62884.000000
mean         7.000875
std          3.155519
min          0.000000
25%          5.000000
50%          7.000000
75%          9.000000
max         15.000000
Name: Store Age, dtype: float64

Sample records:

   StoreKey Order Date  Open Date  Store Age
0        10 2016-01-01 2015-04-04          0
1         0 2016-01-01 2010-01-01          6
2         0 2016-01-01 2010-01-01          6
3         0 2016-01-01 2010-01-01          6
4         0 2016-01-01 2010-01-01          6
5         0 2016-01-01 2010-01-01          6
6        38 2016-01-01 2015-04-04          0
7        38 2016-01-01 2015-04-04          0
8        33 2016-01-01 2015-12-09          0
9        43 2016-01-01 2015-01-01          1

In [35]:
cleaning_log.loc[len(cleaning_log)] = [
    "Sales",
    "Store age",
    "Merged store opening dates and square meters; calculated store age at order date. All 62,884 rows retained, with no missing or negative store ages."
]

display(cleaning_log.tail(3))

,Dataset,Check or Change,Result
9,Sales,Delivery days,Calculated Delivery Days from Order Date and D...
10,Sales,Customer age and age groups,"Merged customer birthdays, calculated age at o..."
11,Sales,Store age,Merged store opening dates and square meters; ...

In [36]:
# Remove exact duplicate entries from the cleaning log
cleaning_log = cleaning_log.drop_duplicates().reset_index(drop=True)

display(cleaning_log.tail(5))
print("Total cleaning log entries:", len(cleaning_log))

,Dataset,Check or Change,Result
7,Stores,Missing Square Meters,1 missing value retained; not replaced with zero
8,Sales,Financial metrics,Merged product prices and costs; calculated Re...
9,Sales,Delivery days,Calculated Delivery Days from Order Date and D...
10,Sales,Customer age and age groups,"Merged customer birthdays, calculated age at o..."
11,Sales,Store age,Merged store opening dates and square meters; ...

Total cleaning log entries: 12

In [37]:
# Group stores by age at the time of each sale
store_age_bins = [-1, 5, 10, 15, float("inf")]

store_age_labels = [
    "0-5 years",
    "6-10 years",
    "11-15 years",
    "16+ years"
]

sales["Store Age Group"] = pd.cut(
    sales["Store Age"],
    bins=store_age_bins,
    labels=store_age_labels
)

# Summarize the distribution
store_age_summary = (
    sales["Store Age Group"]
    .value_counts(sort=False)
    .rename_axis("Store Age Group")
    .reset_index(name="Sales Lines")
)

store_age_summary["Percentage"] = (
    store_age_summary["Sales Lines"] / len(sales) * 100
).round(2)

print(store_age_summary.to_string(index=False))

Store Age Group  Sales Lines  Percentage
      0-5 years        19771       31.44
     6-10 years        36127       57.45
    11-15 years         6986       11.11
      16+ years            0        0.00

In [38]:
cleaning_log.loc[len(cleaning_log)] = [
    "Sales",
    "Store age groups",
    "Created four store-age groups using store age at order date; 62,884 sales lines classified."
]

display(cleaning_log.tail(3))

,Dataset,Check or Change,Result
10,Sales,Customer age and age groups,"Merged customer birthdays, calculated age at o..."
11,Sales,Store age,Merged store opening dates and square meters; ...
12,Sales,Store age groups,Created four store-age groups using store age ...

In [39]:
# Final data-quality audit

print("FINAL SALES DATASET AUDIT")
print("-" * 40)

# Dataset size
print("Rows:", sales.shape[0])
print("Columns:", sales.shape[1])

# Duplicate checks
print(
    "Duplicate rows:",
    sales.duplicated().sum()
)

print(
    "Duplicate Order Number + Line Item:",
    sales.duplicated(
        subset=["Order Number", "Line Item"]
    ).sum()
)

# Check important calculated columns
required_columns = [
    "Revenue USD",
    "Cost USD",
    "Profit USD",
    "Profit Margin %",
    "Delivery Days",
    "Customer Age",
    "Customer Age Group",
    "Store Age",
    "Store Age Group"
]

print("\nMissing values in key analytical columns:")
print(sales[required_columns].isna().sum())

# Check for duplicate column names
print(
    "\nDuplicate column names:",
    sales.columns.duplicated().sum()
)

# Review final column names
print("\nFinal columns:")
print(sales.columns.tolist())

FINAL SALES DATASET AUDIT
----------------------------------------
Rows: 62884
Columns: 24
Duplicate rows: 0
Duplicate Order Number + Line Item: 0

Missing values in key analytical columns:
Revenue USD               0
Cost USD                  0
Profit USD                0
Profit Margin %           0
Delivery Days         49719
Customer Age              0
Customer Age Group        0
Store Age                 0
Store Age Group           0
dtype: int64

Duplicate column names: 0

Final columns:
['Order Number', 'Line Item', 'Order Date', 'Delivery Date', 'CustomerKey', 'StoreKey', 'ProductKey', 'Quantity', 'Currency Code', 'Unit Cost USD', 'Unit Price USD', 'Revenue USD', 'Cost USD', 'Profit USD', 'Profit Margin %', 'Delivery Days', 'Birthday', 'Customer Age', 'Customer Age Group', 'Open Date', 'Square Meters', 'Country', 'Store Age', 'Store Age Group']

In [40]:
from pathlib import Path

# Create a folder for cleaned project files
output_folder = Path("cleaned_data")
output_folder.mkdir(exist_ok=True)

# Save the cleaned datasets
datasets = {
    "Sales_Cleaned.csv": sales,
    "Customers_Cleaned.csv": customers,
    "Products_Cleaned.csv": products,
    "Stores_Cleaned.csv": stores,
    "Exchange_Rates_Cleaned.csv": exchange_rate,
    "Data_Dictionary.csv": data_dictionary,
    "Cleaning_Log.csv": cleaning_log
}

for filename, df in datasets.items():
    file_path = output_folder / filename
    df.to_csv(file_path, index=False)
    print(f"Saved: {file_path} | Rows: {len(df)}")

print("\nAll cleaned datasets saved successfully!")

Saved: cleaned_data\Sales_Cleaned.csv | Rows: 62884
Saved: cleaned_data\Customers_Cleaned.csv | Rows: 15266
Saved: cleaned_data\Products_Cleaned.csv | Rows: 2517
Saved: cleaned_data\Stores_Cleaned.csv | Rows: 67
Saved: cleaned_data\Exchange_Rates_Cleaned.csv | Rows: 11215
Saved: cleaned_data\Data_Dictionary.csv | Rows: 37
Saved: cleaned_data\Cleaning_Log.csv | Rows: 13

All cleaned datasets saved successfully!

In [41]:
import os

print("Your current folder is:")
print(os.getcwd())

print("\nFiles inside cleaned_data:")
print(os.listdir("cleaned_data"))

Your current folder is:
c:\Users\visha\OneDrive\Desktop\Knowvation Learnings\AIML\Python

Files inside cleaned_data:
['Cleaning_Log.csv', 'Customers_Cleaned.csv', 'Data_Dictionary.csv', 'Exchange_Rates_Cleaned.csv', 'Products_Cleaned.csv', 'Sales_Cleaned.csv', 'Stores_Cleaned.csv']